# Generated by Django 3.0.6 on 2024-07-11 21:43

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('button', 'Button'), ('field', 'Field')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('style', jsonfield.fields.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Text Field'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox Group')], max_length=10)),
                ('label', models.CharField(max_length=255)),
                ('options', jsonfield.fields.JSONField(blank=True, default=list)),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='form.Element')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='form.Element')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='form.Form')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='element',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='form.Step'),
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='button', to='form.Element')),
            ],
        ),
        migrations.CreateModel(
            name='FieldSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form.Field')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_submissions', to='form.Submission')),
            ],
            options={
                'unique_together': {('submission', 'field')},
            },
        ),
    ]
